"""Application-level UI protocol.

Defines the contract between the application layer (PanaApp) and anything
that needs to drive the UI — commands, extensions, and the agent layer.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import TYPE_CHECKING, Protocol, runtime_checkable

if TYPE_CHECKING:
    from pana.agents.agent import Agent
    from pana.tui.theme import PanaTheme


@runtime_checkable
class UIContext(Protocol):
    """Protocol describing all public UI operations the application exposes.

    Implemented by :class:`~pana.main.PanaApp`.  Extensions receive a
    ``UIContext`` via :attr:`ExtensionContext.ui` so they can interact
    with the full TUI.
    """

    @property
    def agent(self) -> Agent | None: ...

    @property
    def hide_thinking_block(self) -> bool: ...

    @property
    def hidden_thinking_label(self) -> str: ...

    @property
    def theme(self) -> PanaTheme: ...

    async def select(
        self, title: str, options: list[str], *, timeout: float | None = None
    ) -> str | None: ...

    async def confirm(
        self, title: str, message: str, *, timeout: float | None = None
    ) -> bool: ...

    async def input(
        self, title: str, placeholder: str = "", *, timeout: float | None = None
    ) -> str | None: ...

    def notify(self, message: str, level: str = "info") -> None: ...

    def set_status(self, key: str, text: str | None) -> None: ...

    def set_working_message(self, message: str | None = None) -> None: ...

    def set_hidden_thinking_label(self, label: str | None = None) -> None: ...

    def set_editor_text(self, text: str) -> None: ...

    def get_editor_text(self) -> str: ...

    async def editor(self, title: str, prefill: str = "") -> str | None: ...

    def get_all_themes(self) -> list[dict[str, str | None]]: ...

    def set_theme(self, theme: str) -> dict[str, object]: ...

    def get_tools_expanded(self) -> bool: ...

    def set_tools_expanded(self, expanded: bool) -> None: ...

    def set_title(self, title: str) -> None: ...

    def add_message(self, component: object) -> None: ...

    def remove_message(self, component: object) -> None: ...

    def show_selector(
        self, component: object, focus_target: object | None = None
    ) -> Callable[[], None]: ...

    def update_footer(self) -> None: ...

    def clear_chat(self) -> None: ...

    def stop(self) -> None: ...

    def request_render(self) -> None: ...

    def set_agent(self, agent: Agent) -> None: ...

    def set_hide_thinking_block(self, value: bool) -> None: ...
